### ISSUE TITLE
Pin OLM deployment images to specific versions by default

### ISSUE THREAD

**Issue by fantapsody** [streamnative/terraform-helm-charts#29]
It might be better to use OLM images from a specific release version like [v0.20.0](https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.20.0/olm.yaml) rather than the latest one as in https://github.com/streamnative/terraform-helm-charts/blob/master/modules/operator-lifecycle-manager/chart/values.yaml#L13. I saw some catalog-operator pods were in crash loop because the latest `opm` image is not compatible with the deployment manifests.

**Comment by jrsdav** [comment]
The OLM CRDs were also updated in [v0.7.3](https://github.com/streamnative/terraform-helm-charts/releases/tag/v0.7.3), which fixes the breaking change brought in from updates to their CLI tooling. On new deployments this particular issue shouldn't be a problem, but for older environments the OLM CRDs will need to be manually updated.

That being said, I'm in favor of pinning to a specific release rather than a tag and being more strategic around updates.

**Comment by fantapsody** [comment]
> The OLM CRDs were also updated in [v0.7.3](https://github.com/streamnative/terraform-helm-charts/releases/tag/v0.7.3), which fixes the breaking change brought in from updates to their CLI tooling. On new deployments this particular issue shouldn't be a problem, but for older environments the OLM CRDs will need to be manually updated.
> 
> That being said, I'm in favor of pinning to a specific release rather than a tag and being more strategic around updates.

The breaking change happened again at the time when I created the issue and they just changed how arguments should be specified for their CLI, and the deployment manifests must be changed accordingly in that case. 😅

**Comment by jrsdav** [comment]
Yes! Sorry I misremembered --  the deployment templates in the helm chart (not the CRDs) needed to be updated to account for the change from single hyphenated arguments to double 😅

Releases < v0.7.3 will have that change.
